spring:
  rabbitmq:
    host: localhost
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]
---
spring:
  profiles: docker-compose
  rabbitmq:
    host: rabbitmq
    port: 5672
